version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: twitchstats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/twitchstats
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
      TWITCH_ACCESS_TOKEN: ${TWITCH_ACCESS_TOKEN}
    ports:
      - "8080:8080"
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
